### ISSUE TITLE
Getting undefined method `include?' for nil:NilClass

### ISSUE THREAD

**Issue by wleeperogs** [Diego81/omnicontacts#1]
Seems to be related to rack 1.4 support.  From the current OmniAuth code it appears that line 26 of builder.rb should be:

``` ruby
@ins << @app unless rack14? || @ins.include?(@app)
```

Going to test and if all looks good will submit a pull request.

Thanks

**Comment by etika** [comment]
Why am i still getting this error? 
      @ins << @app unless rack14? || @ins.include?(@app)
