### ISSUE TITLE
Example OmniContacts

### ISSUE THREAD

**Issue by vinhnglx** [Diego81/omnicontacts#109]
Hi @Diego81 , I wrote an article [Using OmniContacts to get mail contacts from Google](http://vinhnguyenle.herokuapp.com/blog/2014/09/11/using-omnicontacts-to-get-mail-contacts-from-google/) and deployed to Heroku: http://omnicontactsvinhnguyen.herokuapp.com/.

You can update your README file.

**Comment by ShaileshPrajapati-BTC** [comment]
can u pls upload the code for importing contact from linkedin using omincontacts gem...
