### ISSUE TITLE
Windows Live API is useless for pulling contacts

### ISSUE THREAD

**Issue by tspike** [Diego81/omnicontacts#11]
I think maybe Hotmail should be removed from the list of supported e-mail services. After spending too much time debugging why omnicontacts was returning an empty array for Hotmail contacts, I realized it's because the API returns this:

```
{
   "data": [
      {
         "first_name": "John", 
         "last_name": "Doe", 
         "name": "John Doe", 
          <snip>
         "email_hashes": [
            "f37cb083473f0fef7f3b4172ccd2ff6070f3e7ccd1752be79c3a2d7ba40decd5"
         ], 
         "updated_time": "2012-08-01T16:29:17+0000"
      }
   ]
}
```

So, in other words, you can't ever get a list of e-mail addresses from it.

http://stackoverflow.com/questions/6785828/get-a-users-contacts-email-phone-addresses-using-windows-live-messenger-connec

**Comment by jamesburke-examtime** [comment]
Was having the same problem, but this gist solved it for me: https://gist.github.com/clouw/5871254
Voilà, email address :)
