### ISSUE TITLE
Is it possible to change the Gmail permissions message to user?

### ISSUE THREAD

**Issue by LucasCioffi** [Diego81/omnicontacts#12]
Hi All,

Is there a way to adjust the message that Google displays to the user?  The problem is that some users might think that the app will edit or delete existing contacts rather than simply making a copy of them.  I looked in https://code.google.com/apis/console/ but didn't find a way to adjust the message.  Thanks!!

Default Message from Google:
[App Name] is requesting permission to:
    Manage your contacts
        View and manage your Google Contacts

**Comment by rewritten** [comment]
@LucasCioffi This has been finally solved in #137 .
