### ISSUE TITLE
Yahoo app shared btw two domains.

### ISSUE THREAD

**Issue by franciscodelgadodev** [Diego81/omnicontacts#125]
Hi all,

I'm having an issue trying to share a Yahoo-app between two different domains. We have our X web-app running and A, B domains pointing to our X web-app. Yahoo allows you to register an app per domain! So, I need to create a yahoo-app for our A domain and one more yahoo-app for our B domain. This will generate two different custumer_id and client_secret tokens, one to each yahoo-app/domain. 

If we have our X web-app using this gem how I can configure it to get both yahoo-apps working? or how can I configure Yahoo to accept two domains in the same yahoo-app(I think this is the best option)? 

Does someone know a workaround for this? Is someone else having the same issue? I've been looking for something like that but I haven't found anything :(

Thanks,
Francisco.

**Comment by rubytastic** [comment]
My first thought would be to make the gem available on a different URL like /contacts and /contacts2 
you need an identifier to hook a certain config too.. 

Basically what you want is a multi config option. 
A config per site entry in yaml or something.

This is currently non supported.
