### ISSUE TITLE
Google does not fetch ALL contacts

### ISSUE THREAD

**Issue by mikeover** [Diego81/omnicontacts#126]
As per https://developers.google.com/google-apps/contacts/v3/#retrieving_all_contacts:

Note: The feed may not contain all of the user's contacts, because there's a default limit on the number of results returned. For more information, see the max-results query parameter in Retrieving contacts using query parameters.

This can be fixed by making multiple consecutive requests using the last index as the next start_index as defined at https://developers.google.com/google-apps/contacts/v3/reference#Parameters.

**Comment by mikeover** [comment]
Worse yet, the first batch of contacts returned from Google are the oldest contacts, some of which I have not communicated with in many years. If my users want to import their contacts into my application, they are going to want to import more recent contacts. 

Please make an update so that this fetches ALL contacts from Google.

**Comment by xacaxulu** [comment]
@mikeover I don't believe that is the desired default behaviour. Please look at the source code here: https://github.com/Diego81/omnicontacts/blob/master/lib/omnicontacts/importer/gmail.rb#L19

In your omnicontacts.rb initializer you can define max_results to be a higher default number.

**Comment by mikeover** [comment]
How exactly can I do that?

**Comment by mikeover** [comment]
Got it - you are right. Perhaps I missed this in the README.
