### ISSUE TITLE
Unable to Fetch Contacts Using Hotmail

### ISSUE THREAD

**Issue by ujjwalkumar** [Diego81/omnicontacts#129]
Hi,

Could you try and see if hotmail is still supported? I'm able to authenticate using hotmail (outlook.com), but I don't see any contacts being pulled.

Thanks,
Ujjwal

**Comment by rubytastic** [comment]
I have no idea if outlook.com changed there policy of getting the data.
Did you managed to find this out already?

**Comment by diegoy** [comment]
It worked for me.

But I couldn't manage to make ngrok work with my application... I just deployed it and tried to import the information on producion

**Comment by loureirorg** [comment]
it worked to me too. It's my first time using omnicontacts and I'm not a hotmail user. But I've created a hotmail account, created an app using omnicontacts, and it worked at the first time that I had tested.

**Comment by jamesburke-examtime** [comment]
This gist worked for me: https://gist.github.com/clouw/5871254

(as referenced in https://github.com/Diego81/omnicontacts/issues/51)
