### ISSUE TITLE
Why don't you change the Gem Version for updates?

### ISSUE THREAD

**Issue by ujjwalkumar** [Diego81/omnicontacts#132]
Hey,

I can see a lot of bugfixes, and for easy updation, will it be possible to update the version number as well, so that it's easy for us to update?

Thanks for the good work!
Ujjwal

**Comment by aleksander-tatskiy** [comment]
+1

**Comment by rubytastic** [comment]
Please send @Diego81  a message or email .
I don't have access to publish a new gem.

**Comment by asmatameem** [comment]
@rubytastic - What do you think about releasing this gem under a different name and then when @Diego81 responds, we can merge it back to the original one?

**Comment by Diego81** [comment]
I have just released a new version of the gem.
Sorry for not being very responsive, now that I have again some more free time, I will make sure to take more care about OmniContacts :)
