### ISSUE TITLE
how should i use max_results?

### ISSUE THREAD

**Issue by echan00** [Diego81/omnicontacts#142]
I am getting server timeouts when downloading the contacts from google. The documentation mentions the possibility of using ':max_results => 1000', but this won't provide all the contacts. 

How am I supposed to overcome this issue?

**Comment by ritec** [comment]
You can increase max results to whatever you want. I am using 10000.

**Comment by echan00** [comment]
@ritec, at 10000 contacts you have not had issues with timeouts? It can take a while sometimes...

**Comment by ritec** [comment]
It's possible but not for me right now, you can put a "loading..." graph or something if you want.
