### ISSUE TITLE
Hotmail scopes

### ISSUE THREAD

**Issue by teodor-pripoae** [Diego81/omnicontacts#147]
Hi,

Is there any reason why this scopes are required [by default](https://github.com/Diego81/omnicontacts/blob/master/lib/omnicontacts/importer/hotmail.rb#L16) for hotmail ? 

I'm trying to setup only import contacts for email/name, is it enough to use `"wl.basic"` ? I need to provide to my users a way to import their friends already using my app and I think any user will ask why I need access to all photos/videos stored on their onedrive account.

![Permissions](https://www.dropbox.com/s/afmaf5sp5a2vi3c/Screenshot%202015-11-09%2019.18.40.png?dl=1)

**Comment by Kentverger** [comment]
I think that you have to use the gem directly from the repo to avoid this problem. `gem 'omnicontacts', github: 'Diego81/omnicontacts'`

**Comment by rubytastic** [comment]
correct needs to be updated ppm @Diego81 
I cannot do this
