### ISSUE TITLE
Yahoo Callback Domain do not allow 'yahoo'

### ISSUE THREAD

**Issue by maxgronlund** [Diego81/omnicontacts#149]
when I go to https://developer.yahoo.com/apps/create/
And set the Callback Domain to digiramp.com/contacts/yahoo/callback
Then the input field turns red and i can see this error message:
"The following strings are not allowed: yahoo, yahoo! and y!"
And the save button is disabled

What am I doing wrong here?
![screen shot 2015-11-18 at 17 38 31](https://cloud.githubusercontent.com/assets/27051/11247332/edb84bdc-8e1b-11e5-826c-a5a31679a1aa.png)

**Comment by rubytastic** [comment]
seems like yahoo does not allow you to have this in your url

**Comment by georgecoltart** [comment]
@maxgronlund in case this is still an issue for you or anyone else - it seems Yahoo only wants the root domain rather than the full path. The path to the callback is passed from the Gem configuration in `omnicontacts.rb`

So in this case you'd be fine with `digiramp.com`
