### ISSUE TITLE
Undefined local variable or method `emails'

### ISSUE THREAD

**Issue by comictvn** [Diego81/omnicontacts#151]
NameError (undefined local variable or method `emails' for #<OmniContacts::Importer::Hotmail:0x007f8b0e9bfc30>):

Could you please fix this issuse 
Thank !

In omnicontacts/importer/hotmail.rb:44 
Fix : contact[:email] = parse_email(emails) if valid_email? parse_email(emails) -> contact[:email] = parse_email(entry['emails']) if valid_email? parse_email(entry['emails'])

**Comment by rubytastic** [comment]
Code not actively maintained please make pull request yourself, 
we do not offer support
