### ISSUE TITLE
Update gem to Rubygem.org

### ISSUE THREAD

**Issue by Kentverger** [Diego81/omnicontacts#157]
The current version of the gem is 0.3.7 and the current version in the repo is 0.3.9 can someone upload the 0.3.9 version to rubygem?

I currently using the gem direct from the repo `gem 'omnicontacts', github: 'moneypool/omnicontacts'` (I make a fork to avoid change in the gem when the master branch have an update)

But I prefer use `gem 'omnicontacts'` only.

**Comment by rubytastic** [comment]
please request @Diego81 
open pulls merged
