### ISSUE TITLE
omnicontacts errors with rack 2 (after upgrading to rails 5)

### ISSUE THREAD

**Issue by joshtobin** [Diego81/omnicontacts#163]
this is the error I get:
undefined method `include?' for nil:NilClass

on line 26 of  omnicontacts (0.3.7) lib/omnicontacts/builder.rb
`@ins << @app unless rack14? || @ins.include?(@app)`

so it seems to me the `rack14?` method should be improved as it now needs to recognise the new major version. I think what it is really looking for is if the version is over 1.3.

If I edit the function to be as below, then it works.

```
   def rack14?
      v = Rack.release.split('.')
      v[0].to_i >= 1 || v[1].to_i >= 4
    end
```

**Comment by teodor2903** [comment]
Thanks!

**Comment by rolme** [comment]
This also fixed my issue. Sent PR #164 based on this suggestion.

**Comment by hugoh1995** [comment]
This problem is not resolved I still have the same issue...

**Comment by sudhirsb2003** [comment]
i am also getting the above error,
did anyone get through the error?
