### ISSUE TITLE
Fetch contacts with pagination

### ISSUE THREAD

**Issue by myakout** [Diego81/omnicontacts#166]
I used the gem to fetch contacts for (Gmail/Yahoo/Outlook), It's working good with me. 
But I need to add pagination when I fetch contacts, or send (limit & offset). 
I asked the [question](http://stackoverflow.com/questions/39250009/fetch-gmail-yahoo-hotmail-contacts-with-pagination-using-omnicontacts) on Stackoverflow, but no answer. 

Can you help me, how can I implement it ?

**Comment by jr180180** [comment]
Hey @myakout - I'm curious as to why you'd need this functionality. You may be better off just storing the contacts after import to your database and then paginating them from there. That way, you only have to do one authorization request.
