### ISSUE TITLE
Yahoo OAuth 2

### ISSUE THREAD

**Issue by Alagaesia93** [Diego81/omnicontacts#169]
Hi guys,
I'm currently integrating your gem in my app and Yahoo does not work. It looks like that Yahoo has updated from OAuth 1 to OAuth 2 (yeah, very fast!). Further explanation here https://www.sourcecoast.com/forums/jfbconnect/jfbconnect-joomla-3x-support/12438-yahoo-api-error#p61158 

Thank you very much and congrats for your gem, it's great!

**Comment by katiemccann** [comment]
Yahoo is still working fine in my app, could you provide a little more detail on the error you're getting?

**Comment by teodor2903** [comment]
Hi, I have same trouble

**Comment by jr180180** [comment]
Tested this with Yahoo today and the integration still works well. I wonder if that `internal_error` was just a temporary thing?

**Comment by CodeAguda** [comment]
I'm encountering this same error, here's the log I got from the gem:
`Error internal_error while processing /contacts/yahoo/callback: {"error":{"@lang":"en-US","@uri":"http://yahoo.com","description":"Access forbidden for the user as cookie validation failed","detail":"Access forbidden for the user as cookie validation failed"}}`

**Comment by katiemccann** [comment]
The cookie validation failure is under a separate issue, since there are no more reports of the original issue, closing this.
