### ISSUE TITLE
Rack version is detected wrong

### ISSUE THREAD

**Issue by dranik** [Diego81/omnicontacts#171]
I'm using rack 2.0.3. My app fails to start because of this method failing to detect Rack version:

`#from lib/omnicontacts/builder.rb`
    `def rack14?`
      `Rack.release.split('.')[1].to_i >= 4` 
    `end`

**Comment by dranik** [comment]
sorry that was not on current master.

**Comment by jr180180** [comment]
Awesome! Glad you got that working @dranik . Should this be closed?

**Comment by dranik** [comment]
Yes, this resolved
