### ISSUE TITLE
LinkedIn connector

### ISSUE THREAD

**Issue by lethunder** [Diego81/omnicontacts#177]
Hello everyone,
i'm not able to get it to work with linkedin. It always return

invalid redirect_uri. This value must match a URL registered with the API Key.

I have verify the key and the redirect_uri.

I don't understand what's going on

**Comment by katiemccann** [comment]
LinkedIn no longer allows access to their connections API unless you are an approved partner.
https://developer.linkedin.com/support/developer-program-transition
