### ISSUE TITLE
Internal Error on Yahoo OAuth

### ISSUE THREAD

**Issue by CodeAguda** [Diego81/omnicontacts#178]
I was receiving this error lately using yahoo oauth:
`Error internal_error while processing /contacts/yahoo/callback: {"error":{"@lang":"en-US","@uri":"http://yahoo.com","description":"Access forbidden for the user as cookie validation failed","detail":"Access forbidden for the user as cookie validation failed"}}`

**Comment by katiemccann** [comment]
If this is still an issue, please provide a demo app that reproduces the issue.

**Comment by kinjalchotaliya** [comment]
I'am getting following error response while authenticating from Yahoo..
Is Yahoo callback  not working with localhost..?
How to specify callback origin in yahoo for local rails server?

> http://localhost:3000

> {
>   "error": "access_denied",
>   "error_description": "InternalOAuthError: Failed to obtain request token (status: 401 OAuth ErrorCustom port is not allowed or the host is not registered with this consumer key."
> }
