### ISSUE TITLE
Cannot import contacts from yahoo.

### ISSUE THREAD

**Issue by bharatvb6** [Diego81/omnicontacts#184]
I am trying to import contacts from yahoo but every time server ends calling failure action. i don't have any clue whats happening. Can some one explain why this is happening.

**Comment by katiemccann** [comment]
You need to provide more details. What is the error message?

**Comment by bharatvb6** [comment]
@katiemccann  One out of five times it it taking me to user authentication page and i am able to import contacts. but most of the time it is redirecting to an page where it says yahoo cannot understand your request and returns 404 bad request or it is getting redirected to the /contacts/failure page with 404 bad request.
I am attaching the screen shot of the error page i am getting.
![yahoo_error_image](https://user-images.githubusercontent.com/29677172/47130914-852e8000-d2b9-11e8-9601-a001fb010a86.png)

**Comment by bharatvb6** [comment]
Hi

I have provided the information about the error which i am facing.

Thank you

**Comment by katiemccann** [comment]
You need to provide details from your app. What does the request look like that you're sending to Yahoo? iWhat error message is being returned? What is the difference between the times it succeeds and fails?
